### ISSUE TITLE
New requirements to the boss

### ISSUE THREAD

**Issue by ghost** [xty1992a/cropper#5]
Does it support rotation of the image or output of the location information of the screenshot box? It might be better to output the location information of the screenshot box because sometimes you need to repeat the cropping on the original image
thanks  This is a very good open source project

**Comment by xty1992a** [comment]
when the cropper render (after you zoom or move),it will emit "change" event with payload like this:
```
{
  "window": {
    "x": 150,
    "y": 100,
    "height": 200,
    "width": 300,
    "top": 100,
    "left": 150,
    "right": 450,
    "bottom": 300
  },
  "model": {
    "x": -33.337500000000034,
    "y": 0,
    "height": 375,
    "width": 666.6750000000001,
    "top": 0,
    "left": -33.337500000000034,
    "right": 633.3375000000001,
    "bottom": 375
  },
  "offset": {
    "x": 183.33750000000003,
    "y": 100,
    "width": 300,
    "height": 200
  }
}
```

you can visit [code pen live demo](https://codepen.io/xty1992a/pen/KKKBoVm).and check out the `preview`.

and the rotation will supported later...
